#!/usr/bin/env python3

import argparse
import sys
import json
from pathlib import Path
import pandas as pd

from backends.hdfc import hdfc_convert_to_ir, hdfc_cc_pdf_convert_to_ir
from backends.sbi import sbi_convert_to_ir
from analyser import kharcha_analysis
from process_ir import assign_types, save_data_in_file

parser = argparse.ArgumentParser(description="Statement Analyzer")

parser.add_argument("--detailed",
                    help="Enable detailed report")
parser.add_argument("--sbi",
                    action="extend", nargs="+", type=str,
                    help="Input is SBI Statement, generated by browser.js (JSON)")
parser.add_argument("--hdfc",
                    action="extend", nargs="+", type=str,
                    help="Input is HDFC/HDFC Credit Card Statement (CSV)")
parser.add_argument("--hdfc-cc",
                    action="extend", nargs="+", type=str,
                    help="Input is HDFC Credit Card Statement (PDF)")
parser.add_argument("--amazon",
                    action="extend", nargs="+", type=str,
                    help="Input is Amazon Pay transactions, generated by browser-amazon-pay.js (JSON)")
parser.add_argument("--json",
                    action="extend", nargs="+", type=str,
                    help="Provide a JSON file for analysis, should be in IR form")
parser.add_argument("--use-ai",
                    action="store_true",
                    help="Use AI to label the data (default: off)")

args = parser.parse_args()

# Amazon statements are being generated using browser scripts, which
# already generates in the IR format, hence treat the input as if passed to
# '--json'
if args.amazon:
    if args.json is None:
        args.json = []

    args.json.extend(args.amazon)
    args.amazon = None

if not (args.sbi or args.hdfc or args.hdfc_cc or args.json):
    print("One of '--sbi'/'--hdfc'/'--hdfc-cc'/'--amazon'/'--json' is required", file=sys.stderr)
    sys.exit(1)

use_ai = args.use_ai

# STAGE 1 - Convert to JSON (our IR) */
# 
# Every backend should give us data in our IR
# (Intermediate Representation), which is an array of
# JSON objects with these keys at minimum:
# 
# {
#    date: String,
#    text: String,
#    debit: Number,
#    credit: Number,
#  ... any other keys/data, like 'balance'/'note' is also okay but not required
#    }
#

global_df = pd.DataFrame(columns=['date', 'text', 'amount'])
if args.json:
    for filepath in args.json:
        output = pd.read_json(path_or_buf=filepath)
        global_df = pd.concat([global_df, output], axis=0, ignore_index=True)

if args.hdfc:
    for filepath in args.hdfc:
        output = hdfc_convert_to_ir(filepath)
        global_df = pd.concat([global_df, output], axis=0, ignore_index=True)

if args.hdfc_cc:
    for filepath in args.hdfc_cc:
        output = hdfc_cc_pdf_convert_to_ir(filepath)
        global_df = pd.concat([global_df, output], axis=0, ignore_index=True)

stage1_output = global_df

# STAGE 2 - Assign Types
stage2_input = stage1_output
stage2_output = assign_types(stage2_input, use_ai)

if stage2_output is None:
    print("Stage 1 can't give an output: Backend did not give valid IR")
    exit(1)

save_data_in_file(stage2_output)

# Stage 3 - Analysis
kharcha_analysis(stage2_output, args.detailed)

