#!/usr/bin/env python3

import argparse
import sys
import json
from pathlib import Path

from backends.hdfc import hdfc_convert_to_ir, hdfc_cc_pdf_convert_to_ir
from backends.sbi import sbi_convert_to_ir
from analyser import kharcha_analysis
from process_ir import assign_types, save_data_in_file

parser = argparse.ArgumentParser(description="Statement Analyzer")

parser.add_argument("--detailed",
                    action="store_true",
                    help="Enable detailed report")
parser.add_argument("--sbi",
                    help="Input is SBI Statement, generated by browser.js (JSON)")
parser.add_argument("--hdfc",
                    help="Input is HDFC/HDFC Credit Card Statement (CSV)")
parser.add_argument("--hdfc-cc",
                    help="Input is HDFC Credit Card Statement (PDF)")
parser.add_argument("--amazon",
                    help="Input is Amazon Pay transactions, generated by browser-amazon-pay.js (JSON)")
parser.add_argument("--json",
                    type=str,
                    help="Provide a JSON file for analysis, should be in IR form")
parser.add_argument("--use-ai",
                    action="store_true",
                    help="Use AI to label the data (default: off)")

args = parser.parse_args()

# SBI and Amazon statements are being generated using browser scripts,
# which already generates in the IR format
# hence, treat the input as if passed to '--json'
if args.sbi:
    args.json = args.sbi
if args.amazon:
    args.json = args.amazon

if not (args.hdfc or args.hdfc_cc or args.json):
    print("One of '--sbi'/'--hdfc'/'--hdfc-cc'/'--amazon'/'--json' is required", file=sys.stderr)
    sys.exit(1)

use_ai = args.use_ai

# STAGE 0 - Convert to formats
if args.json:
    stage0_output = Path(args.json).read_text()
elif args.hdfc:
    stage0_output = Path(args.sbi).read_text()
elif args.hdfc_cc:
    # Pass filepath as it is to stage 1
    stage0_output = args.hdfc_cc
else:
    print("Stage 0 can't give an output: Unknown option passed")

# STAGE 1 - Convert to JSON (our IR) */
# 
# Every backend should give us data in our IR
# (Intermediate Representation), which is an array of
# JSON objects with these keys at minimum:
# 
# {
#    date: String,
#    text: String,
#    debit: Number,
#    credit: Number,
#  ... any other keys/data, like 'balance'/'note' is also okay but not required
#    }
#
stage1_input = stage0_output
if args.json:
    stage1_output = json.loads(stage1_input)
elif args.hdfc:
    stage1_output = hdfc_convert_to_ir(stage1_input)
elif args.sbi:
    stage1_output = sbi_convert_to_ir(stage1_input)
elif args.hdfc_cc:
    stage1_output = hdfc_cc_pdf_convert_to_ir(stage1_input)

# STAGE 2 - Assign Types
stage2_input = stage1_output
stage2_output = assign_types(stage2_input, use_ai)
save_data_in_file(stage2_output)

# Stage 3 - Analysis
kharcha_analysis(stage2_output, args.detailed)

